// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebContext.Pages.Etudiant;

#nullable disable

namespace WebContext.Migrations
{
    [DbContext(typeof(EtudiantContext))]
    [Migration("20220222224147_initial3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebContext.Pages.Etudiant.Etudiants", b =>
                {
                    b.Property<int>("EtudiantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtudiantId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtudiantId");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            EtudiantId = 1,
                            Name = "Achibane",
                            Prenom = "Noureddine"
                        },
                        new
                        {
                            EtudiantId = 2,
                            Name = "Labrag",
                            Prenom = "Hassan"
                        },
                        new
                        {
                            EtudiantId = 3,
                            Name = "Yeah",
                            Prenom = "Mouad"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
